:PROPERTIES:
:ID:       8ccee8c2-774b-484d-afed-c539bfaa7f52
:END:
#+title: Font

* 编码
此章的目的是弄清楚 ASCII, GBK, Unicode, UTF-8 编码的区别，大部分知识都来源于[[https://www.ruanyifeng.com/blog/2007/10/ascii_unicode_and_utf-8.html][这里]]。所以我只是简单转述一下：

ASCII 是最为古老的编码方式，它指的是用一个字节也就是 8 bit 完成编码，实际上只用了 7 bit ，最高位的值衡为 0 （这也成了其他编码方式兼容 ASCII 的一个重要抓手）。也就是说，ASCII 只能编码 2^{7} = 128 个文字，这对英文这种只有 26 个字母的语言体系是足够的。

但是 ASCII 并不能满足很多类似英语的语言体系，比如说 ~é, ג~ 这种字符都是原有的 ASCII 所没有的，但是幸运的是，很多语言的字符数本来就不多，比如俄语是 33 个，而法语是基础的 26 个英文字母加音标。所以这些语言同样可以用一个字节进行编码，英语字符占据了 ~0 ~ 127~ ，它们就占据了 ~128 ~ 255~ 。这样的缺点就是不同国家的 ~128 ~ 255~ 表示不同的字母，彼此之间并不兼容。

但是像汉语这样的语言就没有那么轻松了，他们就算占据了 ~128 ~ 255~ 位，也最多增加 128 个字符，这对于有 10 万个字符的汉语来说是杯水车薪。所以中国就开发了 GB2312 编码系统，后来演变成了 GBK 系统。总的来说，就是采用两个 ~128 ~ 255~ 的字节来表示一个汉字（应该是差不多），这样的话大约可以表示 2 万多个汉字，但是这样其实有一些生僻一些的字也是无法表示的。

这些各个国家私自拓展 ASCII 编码的行为导致了各种语言的编码系统都不兼容，随着互联网的兴起，一套兼容的编码系统呼之欲出，也就是 Unicode ，它用 32bit 表示一个符号，那么就可以表示 2 亿多个符号，这足够容纳人类的所有语言，可以在[[https://symbl.cc/en/unicode-table/][这里]]查询。但是随着而来的问题是，原本需要用 8bit 表示的英文字母，现在需要用 32bit 了，这显然不是一个好事情。

为了权衡数据大小和兼容性，以 Unicode 为编码基础，人们提出了 UTF-8, UTF-16, UTF-32 等具体的编码方案。以 UTF-8 为例，它使用变长编码，压缩了原本 32bit 的字符。在 UTF-8 中，字符可能长度是 8, 16, 32bit ，这样兼顾了大小和兼容性。UTF-16 和 UTF-32 则都是定长编码，UTF-16 适用于需要处理大量双字节字符（如亚洲文字）的场景。UTF-32 则适用于需要处理所有 Unicode 字符，且对内存空间要求较高的情况。

UTF-8 看似兼顾了优势，但是不定长的特性使得解码效率降低，而且这使得像 C++ 这样的语言，字符数组的概念变得容易混淆，当我说 ~s[3]~ 时，很难确定它是一个特定的字符，还只是字符的某一部分。

* 渲染
https://www.jianshu.com/p/8414b96549e3
https://blog.yangteng.me/articles/2019/typography-how-fonts-are-rendered/
* 字族
https://ziyouziti.com/art-1.html
https://www.cnblogs.com/yongdaimi/p/15826975.html
