:PROPERTIES:
:ID:       48c25303-8e2d-41cd-9f0b-191bfdb94484
:END:
#+title: 混合笔记

我对于目前笔记系统不满意，它存在问题（按照重要性排序）：

1. 笔记散、乱、短的特征开始变得明显。这是因为脱离了本科体系化的授课环境。
2. 写笔记的时间变长，这是因为新知识来的太快了，往往了解一个项目就会有很多东西要写。此外还会同时接触很多东西。
3. 笔记中越来越多的复制粘贴，这并不是我懒得思考，只是确实很多知识都只是常识或者规则，也思考不出啥。
4. 浏览查找笔记只能用全站点查找，无法更加直观的表达知识间的联系。
5. ~markdown~ 越来越不能满足我，书写体验不如配置好的 ~org~ 舒服。

如果使用以 ~org-roam, denote~ 为代表的卡片笔记法，则可以解决我目前 *强秩序* 的笔记形式，降低写笔记的成本，充分记录零碎的知识点，更加直观的刻画知识间的联系。但是我担心这是一种 *魔鬼的诱惑* ：

1. 低成本往往对应低收益。虽然确实有“花小钱办大事”的例子，但是往往漫不经心的笔记很容易成为思想懒惰的温床。如果知识间的联系只用一个链接就可以完成，那么我觉得还是有些太简单了。
2. 卡片的强秩序来自于链接的丰富和细致考量，但是这种思考其实还不如一篇长文的树形结构来得直观。
3. 写笔记的成就感降低。 ~org-roam-ui~ 这种展示界面虽然看着很壮观，但是精细到每个节点或者链接总有一种单薄无力的感觉，没有动辄几千上万字的博文更加夺人眼球（我能坚持写作的最重要原因就是觉得看起来很装逼，如果不能给别人看到我情愿不写笔记）。
4. 链接似乎大部分都发生在 =metanote-basenote= 或者 =metanote-metanote= 之间，而缺少 =basenote-basenote= 的形式，也就是说，其实不会有“通过 roam 来获得不曾注意到的联系”的现象，所有的链接都是在有意识的前提下建立的，这就要求勤于 *回顾、整理、重构* 笔记体系。太过于考验自律性了。
5. 迁移和学习成本大。之前写笔记用的是 ~markdown~ ，如果使用 ~org-roam~ ，那么笔记格式就要改成 ~org~ ，博客框架就要改成 ~hugo~ 。此外，之前成体系的笔记也需要被拆解成卡片。
6. 而且如果迁移成功了，就离不开 ~org~ 了，也就是离不开 [[id:7ba3aeb8-f711-4fc8-aac6-5ef4fb647011][Emacs]] 了，也就是不太能心安理得地使用 ~windows~ 了。

所以完全迁移的话，其实是成本大于收益的。不过经过很多的思考，我发现其实可以采用 *树形笔记和卡片笔记* 结合的方法来解决：

1. 将一部分笔记以卡片的形式记录，这部分笔记具有简短、工具性强、直白的特点。比如 code snippet 、Emacs 使用技巧、历史小故事、沟通技巧等。而树形笔记负责体系化更加明显的笔记，比如说研究综述、语法理论、报告讲稿、深度思考的结果、读书笔记和游记等。
2. 将卡片笔记的部分以 ~org-roam-ui~ 的形式发布，作为博客网站的一个链接。保持原本的 [[id:aa310248-f305-487c-a1e8-0d4f8d26e9ca][Hexo]] 和 ~markdown~ 作为树形笔记的展示框架。
3. 掌握 ~org~ 和 ~markdown~ 互相转换的技术，也就是说，这两种笔记并没有明显的界限。不过在设计上，应该是 ~org~ 转 ~markdown~ 偏多一些。
4. 因为 ~markdown~ 的表达能力和 ~hexo~ 的不稳定性，之后可以考虑弃用 ~markdown~ 全面转成 ~org~ ，但是两种笔记相配合的形式不会发生改变。

#+begin_quote
我的身体里住着两个灵魂。

一个是代码人，一个是数学人。

代码人喜欢敲键盘，她觉得打出来的，一行一行排列整齐的才优雅。 不需要字体的变化，也不需要太多大小的变化，标题、黑体、斜体、列表，仅这四样就足以表达我想表达的一切。代码人认为简洁才是优雅。

数学人喜欢用白纸写写画画，最好是 A4 大小，不要装订，白纸上面最好不要有任何线。 数字、公式、图形，横着写、竖着写、斜着写，写大、写小……信手拈来。 笔最好是铅笔，木头铅笔，笔尖削成符合自己心情的形状。数学人认为自由才有灵感。
#+end_quote

