:PROPERTIES:
:ID:       3c978bf4-33e1-4b4a-81ac-88e2f8c94ea7
:END:
#+title: MIPS vs ARM

此文章大量借鉴了这篇[[https://www.sohu.com/a/475207695_166680][新闻]]，如有侵权立刻删除。

在 1984 年，Hennessy 离开斯坦福大学，创立 [[id:437b60d4-fa3f-4dcf-9835-0daf7a58b899][MIPS]] 科技公司。早期的 MIPS 公司发展迅速，始终立于 RISC 技术的潮头。1988 年，MIPS 首款在市场上流行起来的产品 R3000 处理器横空出世。这款处理器销量迅速超过百万颗，不少公司的消费电子产品都用到了 R3000，如[[id:d1b13c89-b59a-4972-baaf-8031f1557519][索尼]]的 PS、[[id:bfba13de-90d4-4dd2-976d-573171e1ccce][思科]]的路由器和 SGI 超级计算机等。美国 [[id:f5f82be3-433a-4737-afd5-ed3da74d615f][DEC]]、爱普生、日本电器等知名企业也都是 MIPS 的客户。

32 位 RISC 芯片产品的成功促进了利用商品化部件生产 *超级计算机* 的进程，同时也启示业界以更高级的 RISC 技术迈向超级计算的顶峰，处理器架构掀起由 32 位向 64 位发展的浪潮。1991 年，MIPS 推出第一款 64 位商用微处理器 R4000。次年底，同时代另一 RISC 架构 [[id:810e5c0e-4843-4fa5-b354-f9fc670b1fde][Alpha]] 问世（由 DEC 开发），全面完成了从 32 位过渡到 64 位技术各项任务。自此，在 MIPS R4000 和 Alpha 21064 处理器引领下，64 位技术应用时代到来。

1996 年，MIPS 推出 R10000 处理器，作为 RISC 阵营的旗舰之一，该处理器投放市场时被认为是世界上最快的 CPU。彼时，已在 CISC 阵营中拔得头筹的英特尔产品与之相比都有所不如。MIPS 产品性能强势若此。根据 MIPS 科技公司的统计，1997 年以 MIPS 架构为基础的 CPU 出货量为 4800 万，占 RISC CPU 总市场份额的 49%。

与此同时，MIPS 最大的竞争对手 ARM 也走出了一条独特的发展道路。早期的 ARM 业绩平平，没能在那个 RISC 架构群星璀璨的年代崭露头角，在此情况下，该公司决定改变产品策略——不再生产芯片，转而以授权方式将芯片设计方案转让给其他公司。这种风险共担、利益共享的模式，使以 ARM 为核心的生态圈形成成为可能。从将产品授权给德州仪器（TI）到迎来首个大客户[[id:30b9e3bb-5bae-45c9-a1a6-fe80632fcc30][诺基亚]]，ARM 搭上了移动手机井喷式普及的特快列车。在此过程中，ARM 与 [[id:28de76a8-415d-458c-a22e-aebac7d3372f][Apple]] 苹果公司深刻的历史渊源，是 ARM 抓住手机智能化机遇的重要因素。iphone 的热销和 [[id:dd934449-c0ff-40ec-996a-ad96f8880f84][Google]] [[id:e3938d33-5497-4640-9901-1a1b1bb66b8f][Android]] 基于 ARM 指令集的事实，让全球移动应用牢牢绑定在 ARM 指令集上。

1998 年，MIPS 和 ARM 上市，而此时，攻守之势易也，ARM 利用 *生态* 飞速发展，而 MIPS 因为自成立之初就面向中高端市场，专注性能，在能耗方面没有 ARM 有优势，因此在移动手机的浪潮中没有把握机遇。同时，MIPS 的架构授权费用比较低，而且并不限制用户对于架构的更改，这样用户就可以自行添加指令，进一步导致了生态破碎化的问题。

这时，一个来自中国市场的机会找上了 MIPS。2001 年，中科院计算所[[id:04645fbf-b8ed-41c2-9687-fced050d376e][龙芯]]课题组成立，致力于国产 CPU 研制。以自主设计为出发点，龙芯课题组看中了架构成熟且可自由更改设计的 MIPS。

2010 年，在北京市和中科院的支持下，龙芯以课题组骨干人员为主体，正式开始龙芯产业化。在此之前，MIPS 科技宣布，中科院计算技术研究所的龙芯中央处理器获得其处理器 IP 的全部专利和总线、指令集授权。2011 年，龙芯中科公司又独立购买了 MIPS 架构授权。

2012 年底，MIPS 被 ARM 和 Imagination 瓜分收购。至此，ARM 一家独大，不过在 2010 年，在[[id:cd1fc793-2938-4fea-b261-fd481341c7e1][加州伯克利]]分校诞生了 RISC-V 开源指令集，以物联网、人工智能等技术浪潮为契机，正在向统治移动市场的闭源指令集 ARM 发起猛烈冲击。

总得来说，MIPS 和 ARM 都起源于 RISC 设计理念诞生之初，最终决定胜负的是两者的生态。一种指令系统承载了一个软件生态，指令系统的胜负，除了本身的性能以外，还要看其生态是否稳固成功。
